<div class="row">
    <div class='list-group gallery'>
        <?php foreach ($viewmodel as $image) : ?>
            <div class='col-sm-4 col-xs-6 col-md-3 col-lg-3'>
                <a class="fancybox thumbnail" rel="ligthbox" href="<?=$image['image']?>">
                    <img class="img-responsive" alt="" src="<?=$image['image']?>"/>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>
