<div class="modal fade bs-example-modal-lg" id="bs-example-modal-edit-post" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form class="form-horizontal" role="form" id="form" method="post" action="<? //=DEF_CONTROLER__LOGIN?>">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel"><?=__('edit')?> <?=ucfirst($this->dataController .' ' . $this->dataAction)?></h4>
                </div>
                <div class="modal-body">
                    <div id="alerts"></div>

                    <?php
                    $textArea = '';
                    if(isset($this->dataEdit)) :
                        $textArea = $this->dataEdit;
                     endif; ?>
                    <textarea  id="editor" contenteditable="true" name="editor" style="overflow: auto; display: none"><?=$textArea?></textarea>

                </div>
                <div class="modal-footer">
                    <input type="hidden" name="dataController" value="<?=$this->dataController?>"/>
                    <input type="hidden" name="dataAction" value="<?=$this->dataAction?>"/>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?=__('cancel')?></button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </form>
</div>
