<?php
$textArea = '';
$button = __('add');
$action = 'insert';
if(isset($this->dataEdit)) :
    $textArea = $this->dataEdit;
    $button = __('save_changes');
    $action = 'update';
endif; ?>
<div class="modal fade bs-example-modal-lg" id="bs-example-modal-edit-post" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form class="form-horizontal" role="form" id="form" method="post" action="<?=createUrl('admin','save')?>">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel"><?=$button?> <?=ucfirst($this->dataController .' ' . $this->dataAction)?></h4>
                </div>
                <div class="modal-body">
                    <div id="alerts"></div>
                    <textarea  id="editor" contenteditable="true" name="editor" style="overflow: auto; display: none"><?=$textArea?></textarea>

                </div>
                <div class="modal-footer">
                    <input type="hidden" name="dataController" value="<?=$this->dataController?>"/>
                    <input type="hidden" name="dataAction" value="<?=$this->dataAction?>"/>
                    <input type="hidden" name="action" value="<?=$action?>"/>
                    <input type="hidden" name="language" value="<?=$_GET['language']?>"/>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?=__('cancel')?></button>
                    <button type="submit" class="btn btn-primary"><?=$button?></button>
                </div>
            </div>
        </div>
    </form>
</div>