<nav class="navbar">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
        <ul class="nav nav-tabs nav-justified">
            <?php
            $collect = array();
            foreach ($this->top_menu as $element) {
                $link[0] = $element['link'];
                if (strpos($element['link'], '/')) {
                    $link = explode('/', $element['link']);
                }
                if (!in_array($link[0], $collect)) {
                    $collect[] = $link[0];
                    echo '<li data-select="' . $link[0] . '"><a href="' . createUrl('admin', 'index') . '/view/' . $link[0] . '"> ' . __($link[0]) . '</a></li>';
                    unset($link);
                }
            }
            ?>
            <li><a href="<?= createUrl('admin', 'logout') ?>"><?= __('logout') ?></a></li>

        </ul>
    </div>
</nav>

<?= $this->viewContent ?>

<script>
    $('.nav-tabs').find('li[data-select="<?=$_GET['view']?>"]').addClass('active');
</script>