<nav class="navbar navbar-default">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
        <ul class="nav navbar-nav">
            <?php
            foreach ($this->top_menu as $element) {
                $link[0] = $element['link'];
                if (strpos($element['link'],'/')) {
                    $link = explode('/', $element['link']);
                }
                echo '<li data-select="'.$element['menu_element'].'"><a href="' . createUrl('admin','index') . '/view/'.$link[0] .'"> ' . __($element['menu_element']) . '</a></li>';
                unset($link);
            }
            ?>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="<?= createUrl('admin', 'logout') ?>"><?= __('logout') ?></a></li>
            <li class="dropdown f16">

            </li>
        </ul>
    </div>
</nav>

<?=$this->viewContent?>
