<div class="container">
    <div class="row login">
        <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 well">
            <form role="form" method="post" action="<?=createUrl('admin','login')?>">
                <div class="form-group text-center">
                    <div class="logo">
                        <span class="glyphicon glyphicon-user set-logo"></span>
                    </div>
                </div>
                <div class="form-group">
                    <input type="text" required="required" class="form-control input-lg" name="userName" id="userid" placeholder="Enter username">
                </div>
                <div class="form-group">
                    <input type="password" required="required" class="form-control input-lg" name="userPassword" id="password" placeholder="Password">
                </div>
                <div class="form-group">
                    <button type="submit" required="required" class="btn btn-default btn-lg btn-block btn-success">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>