<?php if(isset($this->edit) == true) {
    echo '<div class="right edit-bot"><span><i class="glyphicon glyphicon-edit"></i> '.__('edit').'</span></div>';
} ?>
<div style="clear: both"></div>
</div>

</div>
<footer class="footer">
    <div class="container">
        <p class="text-muted">ASowiak 2017 | <a href="<?=createUrl('admin','login')?>" id="pop-upModal"><?=__('admin_footer')?></a></p>
    </div>
</footer>
</body>