<?php
$opts = array();
$uri = '/' . $_GET['controller'] . '/' . $_GET['action'];
foreach (glob("Languages/*.php") as $filename) {
    $lang = str_replace('.php', '', basename($filename));
    $languages[$lang] = __($lang);
    $base_lang = ($_GET['language'] == '') ? DEFAULT_LANG : $_GET['language'];
}
?>
<html lang="<?=$base_lang?>">
<head>
    <meta charset="utf-8">
    <script src="/data/js/jquery-3.2.1.js"></script>
    <script src="/data/js/bootstrap.js"></script>
    <script src="/data/js/app.js"></script>

    <link rel="stylesheet" href="/data/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/data/css/flags16.css">
    <link rel="stylesheet" type="text/css" href="/data/css/site.css">
    <script>
        App.init();
    </script>
</head>
<body>
<?php
if ($this->_session->__isset('flash_message')) {
    echo $this->_session->__get('flash_message');
    $this->_session->__unset('flash_message');
}
?>
<nav class="navbar navbar-default navbar-fixed-top navbar-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= createUrl(); ?>"><?= $this->web_title ?> </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php
                foreach ($this->top_menu as $element) {
                    $link[0] = $element['link'];
                    if (strpos($element['link'],'/')) {
                        $link = explode('/', $element['link']);
                    }
                    echo '<li><a href="' . createUrl($link[0], (isset($link[1])!= NULL) ? $link[1] : 'index') . '"> ' . __($element['menu_element']) . '</a></li>';
                    unset($link);
                }
                ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="<?= __('search_placeholder') ?>">
                    </div>
                    <button type="submit" class="btn btn-default glyphicon glyphicon-search"></button>
                </form>
                <li class="dropdown f16">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false"><?= __('global_header_language'); ?> <?= $languages[$base_lang] ?> <span
                            class="flag <?= $base_lang ?>"></span> <span class="caret"></span></a>
                    <ul class="dropdown-menu langs">
                    <?php
                    foreach ($languages as $langK => $langN) {
                        echo '<li><a href="/' . $langK . $uri . '"><p class="flag ' . $langK . '">' . $langN . '</p></a></li>';
                    }
                    ?>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
<div id="body">
<div class="container">
