<div class="page-header">
    <h1><?=$this->title?></h1>
</div>
<div class="row">

    <div class="col-sm-8 blog-main">

        <div class="blog-post">
                <?=$this->description?>
        </div>
    </div><!-- /.blog-main -->

    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        <div class="row">
            <div class="col-xs-6 col-md-3">
                <a href="#" class="thumbnail">
                    <img src="..." alt="...">
                </a>
            </div>
        </div>
    </div><!-- /.blog-sidebar -->

</div>